googlei18n/TachyFont

build_time/src/main.py

Try to make the log.info and log.debug more useful.

Add a verbose flag to pass to the cleanup code.

---

build_time/scripts/preprocess_font.sh

(right now it is hooked to the OTS validator in my home dir)

add OTS validation

---

run_time/src/gae_server/chrome/js/tachyfont.js

comment out should development/debug messages
remove the old/unused Javascript/CSS loading code.

add timer support for multiple fonts

---

run_time/src/gae_server/chrome/js/tachyfont.js

(the promise made sense in the past when we needed to load JS/CSS)

directly create the manager object rather than using a promise

---

run_time/src/gae_server/chrome/js/tachyfont.js

add a parameter to set the maximum initial visibility time
slight refactoring

add a parameter to control initial visibility

---

run_time/src/gae_server/chrome/js/tachyfont.js

remove the fontname parameter which is available in the fontInfo

---

run_time/src/gae_server/chrome/NotoSansJP_demo.html
run_time/src/gae_server/chrome/js/tachyfont.js

make WebFontTailor limit the result to the number of requested weights

change the API to pass in a list of slant+weight tuples

---

run_time/src/gae_server/chrome/NotoSansJP_demo.html
run_time/src/gae_server/chrome/js/tachyfont.js

also: in the last checkin the WebFontTailor font data was missing.

change the API to a slant+[a set of weights]

---

run_time/src/gae_server/chrome/js/tachyfont.js

Add a function to update a list of TachyFonts.

Add a control to enable using/saving persisted data.

---

run_time/src/gae_server/chrome/js/tachyfont.js

comment out some debug output
set the @font-face to the family name instead of the font name

fixes for closure compiler linting

---

run_time/src/gae_server/chrome/js/tachyfont.js

Also, get rid of an unneeded intermediate function.

Do all the font setting after all the fetching/injecting is done.

---

run_time/src/gae_server/chrome/js/tachyfont.js

Also, get rid of an unneeded intermediate function.

Minor JsDoc nits.

---

run_time/src/gae_server/chrome/js/tachyfont.js

replace console.log with goog.log
fix lint issues

wrap debugging code in "if (goog.DEBUG)"

---

run_time/src/gae_server/chrome/js/tachyfont.js

tachyfont.IncrementalFont.obj_.prototype.loadNeededChars
to
tachyfont.IncrementalFont.obj_.prototype.loadChars

pre-step to refactoring: rename

---

run_time/src/gae_server/chrome/js/tachyfont.js

Change to using a DOM mutation observer (rather than just updated on

---

run_time/src/gae_server/chrome/js/tachyfont.js

Add a second implementation that uses the new url and and glyph bundle format.

Extract backend communication into it's own class.

---

run_time/src/gae_server/chrome/NotoSansJP_demo.html

demo is currently having issues

add goog.require() for Uri

---

run_time/src/gae_server/chrome/js/tachyfont.js

The concern is that a web site could present a short string to the user which is
secret token. The TachyFont request could be used by the server to brute
force determine the secret.

Add to code to obfuscate small requests.

---

run_time/src/gae_server/chrome/js/tachyfont.js

If already persisted then the odds are good that the UI characters have
already been fetched.

Show the font immediately if it is already persisted.

---

run_time/src/gae_server/chrome/js/tachyfont.js

Previously every TachyFont loaded all the chars on the page.

Load just the characters needed by each TachyFont family/weight.

---

run_time/src/gae_server/chrome/js/tachyfont.js

constructor
address lint issues
address Closure compiler issues
clean up tachyfont.promise
make getUrlBase and getPersistedBase private

remove the exportSymbold for tachyfont and get rid of the tachyfont

---

run_time/src/gae_server/chrome/js/tachyfont.js

Refactor the code to add text on a per-font basis.

Add code to walk the DOM to get chars added before the mutation observer is added.

---

run_time/src/gae_server/chrome/js/tachyfont.js

Changer WebFontTailor's weight from number to string.

---

run_time/src/gae_server/chrome/js/tachyfont.js

Minor Javascript style cleanup.
Use TachyFontInfo in Closure annotations.

Workaround for Chrome adding extra single quotes when font-family has spaces.

---

run_time/src/gae_server/chrome/js/tachyfont.js

Add the bug number for the chromium single quotes issue around
font-family name.
Minor style and Closure annotation changes.

Fix the font loading logic: DOMContentLoaded updates immediately, mutation update after 3 sec.

---

run_time/src/gae_server/chrome/js/tachyfont.js

Minor style and Closure annotation changes.

Manage detecting chars, fetching data, and updating the CSS.

---

run_time/src/gae_server/chrome/js/tachyfont.js

Add a class to handle serializing async promises.
Slight tuning of the fetching of char data and setting the CSS.
Minor style and Closure annotation changes.

Set the @font-face CSS avoiding the Flash Of Invisible Text (FOIT).

---

run_time/src/gae_server/chrome/js/tachyfont.js

For slow pages:
- add a pendingChars count to see if the loading of the char data
and/or the setting of the @font-face CSS can be improved
- not yet fully implemented
Minor style fixes

Fix the initial char data loading.

---

run_time/src/gae_server/chrome/js/incrementalfontutils.js
run_time/src/gae_server/chrome/js/tachyfont.js

Fix code that requests char data using multiple requests.

Fix extra quotes issue with CSS font-family.

---

run_time/src/gae_server/chrome/js/tachyfont.js
run_time/src/gae_server/chrome/js/tachyfontset.js

tachyfontset when the related code is.

Move the description of char data loading and setting the font CSS to

---

run_time/src/gae_server/chrome/js/backendservice.js
run_time/src/gae_server/chrome/js/binaryfonteditor.js
run_time/src/gae_server/chrome/js/incrementalfont.js
run_time/src/gae_server/chrome/js/incrementalfontutils.js
run_time/src/gae_server/chrome/js/rledecoder.js
run_time/src/gae_server/chrome/js/tachyfont.js
run_time/src/gae_server/chrome/js/tachyfontpromise.js
run_time/src/gae_server/chrome/js/tachyfontset.js
run_time/src/gae_server/chrome/js/webfonttailor.js

- blank lines between functions
- indenting
- minor jsdoc changes
- semicolons

Only style changes

---

run_time/src/gae_server/chrome/js/tachyfont.js

Fix what should/should-not/cannot be private

Separate out GlyphBundleResponse.

---

run_time/src/gae_server/chrome/js/tachyfont.js
run_time/src/gae_server/chrome/js/tachyfontset.js

Remove TachyFont from INPUT fields.

---

run_time/src/gae_server/chrome/js/backendservice.js
run_time/src/gae_server/chrome/js/closure_deps.js
run_time/src/gae_server/chrome/js/demobackendservice.js
run_time/src/gae_server/chrome/js/fontsinfo.js
run_time/src/gae_server/chrome/js/googlebackendservice.js
run_time/src/gae_server/chrome/js/incrementalfont.js
run_time/src/gae_server/chrome/js/tachyfont.js
run_time/src/gae_server/chrome/js/webfonttailor.js

Upstreams change to split backendservice to demobackendservice and

---

run_time/src/gae_server/chrome/js/tachyfont.js

Convert from global to local most varibles in the debug initialization

---

run_time/src/gae_server/chrome/js/for_debug.js
run_time/src/gae_server/chrome/tachyfont_demos.html

Pass in the right and top offsets to the bandwidth and test size controls.

---

run_time/src/gae_server/chrome/NotoSansJP_100_demo.html

Use webfonttailor.

---

run_time/src/gae_server/chrome/UDHR-JP.html
run_time/src/gae_server/chrome/UDHR-KR.html

Note: these files may need to be updated.

Remove the promise-1.0.0.js as this is now handled by closure.

---

run_time/src/gae_server/www/js/closure_deps.js
run_time/src/gae_server/www/js/misc_utils.js
run_time/src/gae_server/www/js/tachyfont/webfonttailoralternate.js

Add a mechanism to use an alternate server.

---

build_time/scripts/subset_bmp_NotoSansJP-Thin.sh
build_time/scripts/subset_smp_NotoSansJP-Thin.sh
build_time/src/make_subset.py

Add the BMP and SMP subsets (and the source font).

Add a command to subset with Supplementary Multilingual Plane chars

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

make the code more tolerant of fonts with more than one char per seg

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

remove headerInfo variable since the object also has it

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

handle multiple chars using the same glyph Id

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/incrementalfontutils.js

Move parseBaseHeader from a static to a member function.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Minor changes.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontpromise.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

serialize: persist data; request char data; setFont

Use chainedPromise to serialize operations

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

no functional changes (but the diff very hard to understand)

some style changes

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Add debug calls to report the chars and code points.

Fix surrogate support in loadChars.

---

run_time/src/gae_server/www/js/tachyfont/googlebackendservice.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

recognize this call (Chrome already supports it).

Use the tachyfont.utils.stringFromCodePoint since the Closure compiler does not yet 

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Add font name to chainedPromises

Add debug charlist reports.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Add font name to chainedPromises

Minor JsDoc annotation changes.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontutils.js

Add font name to chainedPromises

Replace a String.fromCodePoint() with the tachyfont version.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Move the code that builds a fallback url into tachyfont.js (where the
fonts are handled as a set).

Report when the fonts are available to page (setFont finishes).

---

run_time/src/gae_server/browser_redirector.py
run_time/src/gae_server/www/NotoSansJP_100_demo.html

Move the code that builds a fallback url into tachyfont.js (where the
fonts are handled as a set).

Add a SMP (beyond BMP) character (and fix server redirect).

---

run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js

Make the reporter a singleton class.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Add error reporting to:
incrementalfont.js
tachyfont.js
tachyfontset.js
Add window.onerror reporting.
Modify the time reporting to report time rounded to a 1/20th of a second.
Limit the error reporting URL to the 2000 chars.

Add error reporting

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js
run_time/src/gae_server/www/js/tachyfont/tachyfontutils.js

Add error reporting to:
incrementalfont.js
tachyfont.js
tachyfontset.js
Add window.onerror reporting.
Modify the time reporting to report time rounded to a 1/20th of a second.
Limit the error reporting URL to the 2000 chars.

Add logging and error reporting

---

run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js

Remove the stack info as it might be a privacy issue.
Send multiple reports if the url length would be greater than 2K.
Remove development code.

Let the callers determine the chunking size.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Set the chunking amount.
Make the local reportError routine private.

Add logging calls.

---

run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Add logging calls.
Set the chunking amount.
Add error reports.

Make the local reportError routine private.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontpromise.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Comment out some thenCatch sections that seem redundant.

Make defines for the reportError codes.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontpromise.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Add additional error reporting.

Add logging defines.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Allow updates before the page loads.

Only delay requestUpdateFonts if there was are recent update.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js

Uri encode the name component of logging/error reports.

Cleanup and simplify the error reports.

---

run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontpromise.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Use the id of '000' for error reports that do not apply to a specific

---

run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Set the id for window.onerror to '000'.

Report the time from characters being added to setFont done.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontpromise.js
run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Use ENUM for logging and error values.

Add delete database.

---

run_time/src/gae_server/www/js/tachyfont/fontinfo.js
run_time/src/gae_server/www/js/tachyfont/fontsinfo.js
run_time/src/gae_server/www/js/tachyfont/googlebackendservice.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontpromise.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js
run_time/src/gae_server/www/js/tachyfont/webfonttailor.js
run_time/src/gae_server/www/js/tachyfont/webfonttailoralternate.js

Report lingering operations.
Always indicate the user of a chainedPromise (not just during debug).
Add a separate URL for reporting logging/errors.

Give a more accurate indication of the user miss rate and FOUT experience.

---

build_time/scripts/preprocess_font.sh
build_time/src/font_info.py
build_time/src/info_ops.py
build_time/src/main.py
build_time/src/preprocess.py

Didn't write 'metadata' since preprocess.py already had code that wrote metadata (not called from main though) so wrote 'sha1_fingerprint' instead.

generate sha1 fingerprint

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Check for extra glyphs in the char data.
Handle updating the charlist more carefully.

Check the charlist vs cmap and glyf table.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Fix document.fonts.load for weights not a multiple of 100.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Have checkCharacters return a success/fail value.
Cleanup names of some of the constants.
Cleanup some variable names.

Check the format 12 cmap for the chars in the charList.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Read the persisted charList at the same time as the font data.

Do not use the persisted data if it has a problem.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Fix binding this to a function.

Fix the index when there are multiple chars per glyph.

---

run_time/src/gae_server/incremental_fonts.py

Assume '0' for the bandwidth value if no 'X-TachyFont-bandwidth' header

---

run_time/src/gae_server/www/js/tachyfont/demobackendservice.js
run_time/src/gae_server/www/js/tachyfont/glyphbundleresponse.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontutils.js

- Most of the removed code was used during initial development.
Make the copyright exactly the same.
- The compiled versions keep the full copyright and if they are exactly
the same
- then gzip can better compress them.

Remove unneeded code.

---

build_time/scripts/preprocess_NotoSansJP-Thin_subset_bmp.sh
build_time/scripts/preprocess_NotoSansJP-Thin_subset_smp.sh
build_time/scripts/preprocess_NotoSansJP.sh
build_time/scripts/subset_bmp_NotoSansJP-Thin.sh
build_time/scripts/subset_smp_NotoSansJP-Thin.sh

Add comments that the scripts are designed for use in the open source

---

run_time/src/gae_server/incremental_fonts_utils.py

This is (mostly) commented out.

Add code to generate a hex dump of the glyph bundle data.

---

run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/TachyFontServlet.java

This whole file is likely to go away.

Comment out unused variables.

---

run_time/src/gae_java/TachyFont/war/WEB-INF/web.xml

Add the mapping to the base.
Hacking around the glyph data mapping.

Add the gen_204 mapping.

---

run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/GetCharData.java

Write a preliminary fontname to font JAR file routine.

Read the char request data using Gson.

---

run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/GetBase.java

Get the fontname from the request.
Add copyright.

Use TachyFontData to get the base data.

---

run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/GetCharData.java

Uset Gson to get the fontname and codepoints from the request.
Add copyright.

Use TachyFontData to get the glyph data.

---

run_time/src/gae_java/TachyFont/war/WEB-INF/web.xml

Now have getBase and getCharRequest servlets to remove the generic

---

run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/CharRequest.java
run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/Gen204.java
run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/GetBase.java
run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/GetCharData.java
run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/GlyphEntry.java
run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/GlyphsInfo.java
run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/TachyFontData.java

Add JavaDocs.

---

run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/GetCharData.java
run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/TachyFontData.java

Clean up some commented out code.

Add some JavaDoc comments.

---

run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/gae/server/Gen204.java
run_time/src/gae_java/TachyFont/war/WEB-INF/web.xml

Move Gen204 into the gae/server dir.

Fix the servlet paths.

---

run_time/src/gae_server/incremental_fonts.py
run_time/src/gae_server/incremental_fonts_utils.py

- magic number
- major/minor version number
- reserved field
- SHA-1 font file fingerprint

Add the following to the char data (glyph bundle):

---

run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js
run_time/src/gae_server/www/js/tachyfont/demobackendservice.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Add code to handle these fields in the char data (glyph bundle) request
- magic number
- major/minor number
- reserved field
- fingerprint

Add code to handle and check the font file fingerprint.

---

run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/TachyFontData.java

Add these fields to the char data response:- magic number
- major/minor version
- reserved
- fingerprint

Add fingerprint to the char data response

---

build_time/src/cmap_compacter.py

existing code results to the class results.

Create a class that uses bitarray to do the bit handling and compare the

---

build_time/src/cmap_compacter.py

Use a local class instead of BitVector.

If bitarray can be imported then compare the results.

---

run_time/src/gae_server/incremental_fonts_utils.py

This is useful for test writing and debugging.

Add code do a hex dump of a file.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Leave in the core logic but move the details out into separate routines:
* calcNeededChars_
* fetchChars_
* injectChars_
Fix a minor unbound 'this'.

Refactor tachyfont.IncrementalFont.obj_.prototype.loadChars.

---

run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Breaking up loadFonts into a more manageable size: move initialization

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Rename getUrlBase to getBaseFontFromUrl.
Rename allLoaded to waitForPrecedingPromise.
Refactor loadFonts:
* move the code that gets the base font into a separate function.
* move the code that uses the TachyFont font into a separate function.
* move the code that sets up the text listeners into a separate
function.

Rename getPersistedBase to getBaseFontFromPersistence.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Remove an unneeded then clause.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

This is small enough to be loaded very early.
This code can only load font data that is already persisted.

A very small library to early load TachyFonts.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

Record the prelude activities with times (instead of just recofding

---

run_time/src/gae_server/www/js/tachyfont/browser_chrome.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

@font-face rule instead of just a single component.
Make a routine to close the database.
Minor cleanups.

Close the handles to indexedDB in TachyFontPrelude

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Slight tuneup to window.onerror event handler.

Add an error report for when delete IDB fails.

---

build_time/scripts/preprocess_NotoSansJP-Thin_subset_a24z.sh
build_time/scripts/subset_a24z_NotoSansJP-Thin.sh
build_time/src/font_dev_utils.py
run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Slight adjustment of the code to hex dump data bytes.
Scripts to subset and preprocess a 26 char (a-z) subset of NotoSansJP-Thin.
Add code to read a string. 
Make the getOffset method public.

Report the priority font weights separately (eg, the 100 weight).

---

run_time/src/gae_server/www/js/closure_deps.js
run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js
run_time/src/gae_server/www/js/tachyfont/cmap.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js
run_time/src/gae_server/www/js/tachyfont/tachyfontutils.js

tachyfont defines several functions used by files that it goog.requires. 
Move the functions into tachyfont.utils.

Break some circular dependencies:

---

run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js

Add more CFF DICT operator mappings.
Add a test routine to enable debug logging output.

Add CffDict.loadDict and make CffDict.prototype.init private.

---

run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js

* change key to operator
* change value to operands
* add getOperands method
* store the nibble value as a number

DICT changes:

---

run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_dict.js

per font private DICTs.
Add enums for the CFF DICT operators.

Add code to read the CharString INDEX, FontDict (FDArray) INDEX, and the

---

run_time/src/gae_server/www/js/tachyfont/sfnt.js

Add code to replace a table.
Add a test routine to check that a font passes OTS.

Add a tachyfont.Sfnt.Font class to manage the tables in a font.

---

run_time/src/gae_server/www/js/tachyfont/cff.js

understood the CFF table but is not needed to resize the CharStrings
INDEX.
Add code to get a block of the CFF data.

Remove/simplify some of the parsing that was coded while verifying I

---

run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_dict.js

Add routine to update a DICT operand.

Add routine to update the CharString INDEX size.

---

run_time/src/gae_server/www/js/tachyfont/sfnt.js

In sfnt.js:
- add CompactOffsets which will be used by Compact TachyFOnt
- define some table tags
- rename newFontData to newFontBytes since it is an Uint8Array
- add a convience routine
- getTableLength

add CompactOffsets which will be used by Compact TachyFOnt

---

run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Remove duplicate lines.
No functional change.

Separate out setting a single font from setting a group of fonts.

---

run_time/src/gae_server/www/js/tachyfont/fontsinfo.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Sort the priority fonts to the beginning of the list.

Load the TachyFonts in series rather than in parallel.

---

run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js

Change hdrSize_ to headerSize_.
Remove unused nGlyphs_.
Change offSize_ to offsetSize_.

Add CFF to descriptions of CFF elements.

---

run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js
run_time/src/gae_server/www/js/tachyfont/cmap.js
run_time/src/gae_server/www/js/tachyfont/glyphbundleresponse.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/incrementalfontutils.js
run_time/src/gae_server/www/js/tachyfont/sfnt.js
run_time/src/gae_server/www/js/tachyfont/tachyfontutils.js

Change binEd to binaryEditor.

---

run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js
run_time/src/gae_server/www/js/tachyfont/sfnt.js

Add a function to get an INDEX's size without actually loading it.
Rename some functions.
Changes comments.
Renames some variables.

Remove not (currently) used private variables.

---

run_time/src/gae_server/www/js/tachyfont/backendservice.js
run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js
run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js
run_time/src/gae_server/www/js/tachyfont/cmap.js
run_time/src/gae_server/www/js/tachyfont/fontsinfo.js
run_time/src/gae_server/www/js/tachyfont/glyphbundleresponse.js
run_time/src/gae_server/www/js/tachyfont/googlebackendservice.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/incrementalfontutils.js
run_time/src/gae_server/www/js/tachyfont/rledecoder.js
run_time/src/gae_server/www/js/tachyfont/sfnt.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js
run_time/src/gae_server/www/js/tachyfont/tachyfontutils.js
run_time/src/gae_server/www/js/tachyfont/webfonttailor.js
run_time/src/gae_server/www/js/tachyfont/webfonttailoralternate.js

Remove the "." from "Array.<" and "Object.<".
Add space to "something,something".
Remove some blank lines.
Remove "@dict" from member variables.
Change "An shorter" to "A shorter".

Add "@const" to member variables that should not be changed.

---

run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js

Remove some DEBUG code.
Change some comments.

Remove the dict oOperators: it was a debugging aid.

---

run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js
run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js
run_time/src/gae_server/www/js/tachyfont/sfnt.js

- make the instance variables private
- add accessor functions
- add comments
In cff_dict.js add accessor functions.
Remove some routines that were useful during development .

In binaryfonteditor.js

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js
run_time/src/gae_server/www/js/tachyfont/tachyfontprelude_ja.js

- remove unused local variable.
- change return value.

Address compiler warning/error issues:

---

run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js
run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js

and add an accessor for offset and rename the existing getOffset to
getElementOffset

In BinaryFontEditor make the offset instance variable private

---

run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Add a check in loadFonts to see if the current browser has the features

---

run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js
run_time/src/gae_server/www/js/tachyfont/sfnt.js

Fix type errors and some warnings.
To cff_index.js add an accessor to get the offset to then INDEX in the
CFF table.

Change the tachyfont.Cff constructor so there are no undefined values.

---

run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js
run_time/src/gae_server/www/js/tachyfont/cmap.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/persist_idb.js
run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Fix the errors and some of the warnings.

Add accessors.

---

run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js

Move the parsing of the CFF DICT elements into the tachyfont.CffDict
constructor.

Move the parsing of the CFF table into the tachyfont.Cff constructor.

---

run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js

- Rename getOffset to getOffsetToIndex.
- Rename getCount to getNumberOfElements.
- Simplify computeLength by using the constructor.
Work on function docs.

In cff_index.js

---

run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js

issue is a library fatal issue.

Move the exception handling to the level where it is clear that the

---

run_time/src/gae_server/www/NotoSansJP_demo.html

Fix Closure issue.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

Since it is only used once de-subroutinize getBlobUrl.
Minor doc changes.

Minor comment changes.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

Rename getDbBase to getFontBase.

Chain the font load operations in the main call.

---

run_time/src/gae_server/www/js/tachyfont/demobackendservice.js

Change demobackendservice.js to pass in font name and weight instead of

---

run_time/src/gae_server/www/js/tachyfont/fontinfo.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/webfonttailor.js

5b4533158f49cc98e4168651fcb74747783a3280

There appear to be errors so undo

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/sfnt.js

In incrementalfonts.js rename isCFF to isCff.
Change comments.
Minor change to a debug report.

In sfnt rename getTableData to getTableBytes.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

and from constructor to function
Add more error codes.

Rename tachyfontprelude.TachyFontPrelude to tachyfontprelude.preload_

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

Handle font.load issues from loading fonts that block the browser from

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

Rename newFontInfo to FontInfo.
Use an anonymous function to scope the variables and functions.
Inline the getDbName code.

Code reorg/cleanup; no functional changes.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

Include a tiny placeholder font in the prelude code to keep OTS from

---

run_time/src/gae_server/www/js/tachyfont/persist_idb.js

When the IndexedDB version changes do not delete the existing

---

run_time/src/gae_server/www/js/tachyfont/persist_idb.js

Initialize the char list table.

Simplify the initialization of the metadata table.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/persist_idb.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Adjust log/error names to avoid duplication.

Sync client/server log/error codes.

---

run_time/src/gae_server/www/js/tachyfont/persist_idb.js

Distinguish between a unfinished previous save and an initial save (save

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

day. This avoids using TachyFont on systems that have an auto cleaner
that deletes the saved data.

Only load the font data if it has been stable in persistent store for a

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/persist_idb.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Tolerate missing metadata.
Remove debug code.

Add @struct to tachyfont.IncrementalFont.obj.

---

run_time/src/gae_server/www/js/tachyfont/cmap.js

to be low frequency. However, it turned out to be a noisy report.

Stop reporting "already set". This was never an error but was expected

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Add initial controls for Compact TachyFont.
Move the setting of the Hmtx/Vmtx into a subroutine.

No functional changes.

---

run_time/src/gae_server/www/js/tachyfont/persist_idb.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontutils.js

Initial code to check for stable persistence at a global level rather

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

Rename the error codes to include 'PRELUDE'.

Change the stable time to 48 hours.

---

run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Allow errors to return a Promise resolve(null) instead of a Promise

---

run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Separate the initialization of the FontsInfo URLs.
Separate the initialization of the TachyFont Reporter.
Add reject handling.
In isSupportedBrowser() report individual errors.

Pre work for checking in code to add a global persistance check.

---

run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Add a page load report so the error rates can be compared to the page

---

run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_dict.js

bytes.
Add typedefs for a DICT operand and operand.

Make the DICT operand a record type holding the value and number of

---

run_time/src/gae_server/www/js/tachyfont/backendservice.js
run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js
run_time/src/gae_server/www/js/tachyfont/browser_chrome.js
run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js
run_time/src/gae_server/www/js/tachyfont/cmap.js

Minor comment changes.
No functional changes.

Make sure comments at the end of the line are preceded by 2 spaces.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

Add explicit nullability.

---

run_time/src/gae_server/www/js/tachyfont/cff.js
run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cff_index.js

JsDoc changes.
Minor logic changes.
Changed error message.
Whitespace changes.

Remove @throws.

---

run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js
run_time/src/gae_server/www/js/tachyfont/tachyfontutils.js
run_time/src/gae_server/www/js/tachyfont/typedefs.js

Add new typedefs.
In binaryfonteditor rename 'font' to 'fileInfo'.

Move many of the typedef statements into typedefs.js.

---

run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js
run_time/src/gae_server/www/js/tachyfont/cff_dict.js
run_time/src/gae_server/www/js/tachyfont/cmap.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/incrementalfontutils.js
run_time/src/gae_server/www/js/tachyfont/typedefs.js

Make a typedef for CmapMapping.

Move getCmapMapping from incrementalfontutils.js to binaryfonteditor.js.

---

run_time/src/gae_server/www/js/tachyfont/binaryeditor.js
run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js

Move the simple binary editing functions from BinaryFontEditor to

---

run_time/src/gae_server/www/js/tachyfont/cmap.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/persist_idb.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontutils.js

Add 'compact' to the name of the datastore holding the compact file
info.

Get cmapMapping from fileInfo.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

being done here with no code changes so that a real code change coming
soon will not be totally obfuscated by the clang formatter changes.

No code changes. Just use the really ugly clang formatting. This is

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont_defines.js

Add a define for tachyfont.Define.compactStoreNames.
Minor changes to tachyfont.loadFonts_loadAndUse.

Move persist_idb_test and persist_idb_test_utils under tachyfont.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Add an accessor function for fontInfo.

Make setMtx reusable for both regular and Compact TachyFont.

---

run_time/src/gae_server/www/js/tachyfont/compactcff.js
run_time/src/gae_server/www/js/tachyfont/sfnt.js

When compacting a CompactCff update the FileInfo.

Add FileInfo and FontInfo to the CompactCff object.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/incrementalfontutils.js

Move setMtx to incrementalfontutils.js to make it reusable in

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

caller.
Separate the glyphIdToCodeMap logic into a subroutine.

Make injectChars a simple subroutine by moving the promise code into the

---

run_time/src/gae_server/www/js/tachyfont/compactcff.js

Separate the glyphIdToCodeMap logic into a subroutine.

Make injectChars a simple subroutine by moving the promise code into the caller.

---

run_time/src/gae_server/www/js/tachyfont/compactcff.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/persist_idb.js
run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js

Straighten out the tachyfont.CompactCff.injectChars error handling.
Pass reportError the error/event object and let it find the info.

Move the inject retries up a level so it uses a new transaction.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/synchronous_resolution_promise.js

- handle multple 'then' calls on a given promise.
Add info to compactRecord when get getCompactFontFromPersistence rejects.
Clear compactRecord after injectCompact.

Fix SynchronousResolutionPromise to handle goog.Promise

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Catch issues from getCompactFont and report success/failure.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Have getCompactFont resolve the compactCharList.
Have injectCompact wait for compactCharList to resolve before reading the database.

Change the compactCharList from an Object to a promise.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Add code to beging enabling use (display) of Compact TachyFont.

---

run_time/src/gae_server/www/js/tachyfont/message_queue.js

This will remove the need for locking for updates as only one will run at a time.

Initial checkin of a class to support handling updates as a queue.

---

run_time/src/gae_server/www/js/tachyfont/work_queue.js

To WorkQueue add an addTask call.

Add a Task class.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

- remove unneeded members
- make the members private
- add accessors for the private members

In incrementalfont.obj:

---

run_time/src/gae_server/www/js/tachyfont/compactcff.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Add tests to see if injectGlyphBundle is throwing exceptions.

Add tests to see if Uint8Array.from is a valid function.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js

Had to remove the non-compact injection code.

Stop storing FontInfo on IncrementalFont.

---

run_time/src/gae_server/www/js/tachyfont/compactcff.js
run_time/src/gae_server/www/js/tachyfont/persist_idb.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontpromise.js

Fix conformance errors, mostly unknownprops.

Check window.location.port is non-null.

---

run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontpromise.js

Replace setInterval with setTimeout.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

This reduces the load time about 1/2.

Load the fonts in parallel rather than serially.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

Rename load to loadFont.
Change loadFont to return true if all the fonts are available in persistent store.
Record DomMutationObserved and DOMContentReady.

Add XHR load URL function.

---

run_time/src/gae_server/www/js/tachyfont/compactcff.js
run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/persist_idb.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Replace openIndexedDB with openIndexedDbSynchronousResolutionPromise.
Rename openIndexedDbSynchronousResolutionPromise to openIndexedDb.
Remove the TachyFontDropData url option.
Remove unused constants.

Remove the db handles that were left open continuously.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/persist_idb.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Remove the TachyFontDropData url option for global data.
Remove old code to fonts stored uncompacted issue.

Close the db handle in getCompactFontFromPersistence.

---

run_time/src/gae_server/www/js/tachyfont/persist_idb.js
run_time/src/gae_server/www/js/tachyfont/synchronous_resolution_promise.js

Add tachyfont.SynchronousResolutionPromise.all to support multiple parallel reads.

Read multiple stores from the DB in parallel rather than in series.

---

run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js

Remove the 'loaded' value as it is no longer used.

In prelude make separate functions for fetching text vs binary.

---

run_time/src/gae_server/www/js/tachyfont/launcher.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfontset.js

Reorder args to launcher.loadFonts and launcher.loadTachyFonts.

Add automatic CSS injection.

---

run_time/src/gae_server/www/js/tachyfont/browser_chrome.js

Delete the old font blobUrl after the new one is ready.

Use FontFace to load fonts instead document.fonts.load().

---

run_time/src/gae_server/www/js/tachyfont/backendservice.js
run_time/src/gae_server/www/js/tachyfont/demobackendservice.js
run_time/src/gae_server/www/js/tachyfont/googlebackendservice.js
run_time/src/gae_server/www/js/tachyfont/googlecloud_backend.js
run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js

Move the reporting Url code into the backend handling code.

Pass a backend handle into the reporter.

---

run_time/src/gae_server/www/js/tachyfont/backendservice.js
run_time/src/gae_server/www/js/tachyfont/demobackendservice.js
run_time/src/gae_server/www/js/tachyfont/googlebackendservice.js
run_time/src/gae_server/www/js/tachyfont/googlecloud_backend.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Add the app name so monitoring can report which app is sending the status.

Add metric/error reporting to the Google Cloud backend handler.

---

run_time/src/gae_server/www/js/tachyfont/error_report.js
run_time/src/gae_server/www/js/tachyfont/googlecloud_backend.js
run_time/src/gae_server/www/js/tachyfont/metric_report.js

Change the client object field names to match the proto.

Add a timeout and onunload to flush the queued status reports.

---

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Change loadFonts to actually wait for the code to finish before resolving its promise.

Move the initial font display to the setup of the text listeners.

---

run_time/src/gae_server/www/js/tachyfont/merged_data.js
run_time/src/gae_server/www/js/tachyfont/tachyfont.js

Add a comment on why the fonts are loaded in serial rather than parallel.

Use the higher level object to decide if merged fontbases are available.
