run_time/src/gae_server/chrome/js/tachyfont.js
also: in the last checkin the WebFontTailor font data was missing.
=> remove an unnecessary comment to fix lint warning

run_time/src/gae_server/chrome/js/tachyfont.js
Previously every TachyFont loaded all the chars on the page.
=> Load just the characters needed by each TachyFont family/weight.

run_time/src/gae_server/chrome/js/tachyfont.js
This allows the font name to be varied per weight.
=> Use family name instead of font name when requesting data.

run_time/src/gae_server/chrome/js/tachyfont.js
Minor Javascript style cleanup.
Use TachyFontInfo in Closure annotations.
=> Workaround for Chrome adding extra single quotes when font-family has spaces.

run_time/src/gae_server/chrome/js/closure_deps.js
It currently defines tachyfont.BinaryFontEditor.
=> Move the tachyfont.BinaryFontEditor out of tachyfont.js and into a separate file.

run_time/src/gae_server/www/js/tachyfont/incrementalfontutils.js
ignore characters above 0xFFFF.
=> Format 4 fixes: use the correct index when setting the glyph Id and

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js
segment. Having just one char per segment makes it easy to make the cmap
accurately indicate the characters loaded in the TachyFont.
=> Add code to determine if the font has a cmap that has one char per

build_time/src/base_fonter.py, build_time/src/cmap_compacter.py, build_time/src/fontTools_wrapper_funcs.py, build_time/src/info_ops.py
=> Accurate cmap for TachyFont

run_time/src/gae_server/www/js/closure_deps.js
Move the code that builds a fallback url into tachyfont.js (where the
fonts are handled as a set).
=> Report when the fonts are available to page (setFont finishes).

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js, run_time/src/gae_server/www/js/tachyfont/tachyfontset.js
Report the time from TachyFont creation to switching the font for DOMContentLoaded.
Remove the duplicate count number from the logging and errors.
Remove bucketizing.
Remove the deprecated tachyfont.updateFonts call.
=> Change most time reporting to relative to start of TachyFont or char data available.

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfontpromise.js, run_time/src/gae_server/www/js/tachyfont/tachyfontset.js
- Put the type at the beginning.
- Use uppercase as the individual characters are more distinct.
=> Make the logging and error name parameters more legible.

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
Make sure the setFont lock is released even if the operation fails.
=> Tolerate charlist not being persisted when the base being persisted.

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
(missed in the earlier checkin).
=> Make sure the setFont lock is released even if the operation fails

run_time/src/gae_server/www/js/tachyfont/tachyfont.js
This is a prepatory step to reduce the 'noise' before changing the
window.onerror handling.
=> Move the error reporting code to the top of the file (no changes).

build_time/src/cleanup.py, build_time/src/fontTools_wrapper_funcs.py
Currently some code in the _c_m_a_p file of the copy of ttLib under gae_server
is commented out / changed to avoid coalescing cmap runs.  In order to use
the upstream ttLib, the quick thing to do is handle this like the other ttLib
patches.
The only call that relies on this in the build_time is in cleanup.py.
This does not revert the original corresponding patch to _c_m_a_p
since I do not know if there's any runtime code that relies on it.  That
patch also changed an additional function, which this change does not
reimplement since it is not called from the build time code.
=> Wrap ttLib cmap code that constructs format 12/13 tables.

run_time/src/gae_java/TachyFont/src/com/github/googlei18n/tachyfont/GetCharData.java
Switch to a font with closure data.
Make up a set of requested chars including a surrogate and a char with
multiple closure glyphs.
Remove some of the read-cmap development code.
Add code to read the glyph closure info.
Starting to create the glyph bundle.
Convert input/output parameters to more generic types.
Change the HashMap objects to TreeMap to get sorting.
Now that the gids are sorted: when parsing the closure data get rid of
the ByteArrayOutputStream.
=> Work in progress: coding the char data response code.

run_time/src/gae_server/www/js/tachyfont/browser_chrome.js
setting the whole @font-face rule instead of just a single component.
The last checkin was actually: Close the DB after use.
=> Close the handles to indexedDB in TachyFontPrelude

run_time/src/gae_server/www/js/tachyfont/tachyfont.js
Set the debug level to WARNING unless the url parameter is set. This way
clients can set the debug level without getting noise from TachyFont
=> 'Namespace' TachyFont's debug messages.

run_time/src/gae_server/www/js/tachyfont/fontinfo.js, run_time/src/gae_server/www/js/tachyfont/googlebackendservice.js
Rename getfamilyPath to getFamilyPath.
Slight tuning of JsDoc parameters.
=> add a priority flag to the font so it can be handle before the non-priority fonts.

run_time/src/gae_server/www/js/closure_deps.js, run_time/src/gae_server/www/js/tachyfont/browser_chrome.js, run_time/src/gae_server/www/js/tachyfont/cmap.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/incrementalfontutils.js, run_time/src/gae_server/www/js/tachyfont/persist_idb.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfontlogger.js, run_time/src/gae_server/www/js/tachyfont/tachyfontpromise.js, run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js, run_time/src/gae_server/www/js/tachyfont/tachyfontset.js
- tachyfont.js provides tachyfont.logger to the same files that it
goog.requires. 
- Move the logger to a separate class/file.
Add some missing goog.require statements.
Remove some unneeded goog.require statements.
Remove or comment out some unneeded variables.
=> Remove the circular dependency of tachyfont.logger.

run_time/src/gae_server/www/js/tachyfont/cmap.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/persist_idb.js, run_time/src/gae_server/www/js/tachyfont/sfnt.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfontpromise.js, run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js, run_time/src/gae_server/www/js/tachyfont/tachyfontset.js
- tachyfont.js provides tachyfont.logger to the same files that it goog.requires. 
- Move the logger to a separate class/file.
Add some missing goog.require statements.
Remove some unneeded goog.require statements.
Remove or comment out some unneeded variables.
=> Break the tachyfont.reporter circular dependency.

run_time/src/gae_server/www/js/tachyfont/backendservice.js, run_time/src/gae_server/www/js/tachyfont/demobackendservice.js, run_time/src/gae_server/www/js/tachyfont/fontsinfo.js, run_time/src/gae_server/www/js/tachyfont/glyphbundleresponse.js, run_time/src/gae_server/www/js/tachyfont/googlebackendservice.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/persist_idb.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfontutils.js
variables.
Add a could tests for tachyfontutils.
Fix goog.provide/goog.require per gjslint.
Minor cleanups per gjslint.
=> Break a circular dependency for several tachyfont.IncrementalFont

run_time/src/gae_server/www/js/tachyfont/cff.js, run_time/src/gae_server/www/js/tachyfont/cff_index.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfontprelude.js
Remove unused encodingsOffset field.
Change some comments.
Remove commented out code that was move to a different file in a
previous
checkin.
=> Add a CffIndex.TYPE_BINARY_STRING type rather than passing an isBinary.

run_time/src/gae_server/www/js/tachyfont/cff.js, run_time/src/gae_server/www/js/tachyfont/cff_index.js, run_time/src/gae_server/www/js/tachyfont/sfnt.js
To avoid an extra copy of the (multi-megabyte) CharStrings INDEX pass it
in as an array-of blocks => When replacing a table pass in a array-of
array-of data blocks.
=> To CffIndex add a getDictElement that checks the INDEX type.

run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js, run_time/src/gae_server/www/js/tachyfont/cff_index.js, run_time/src/gae_server/www/js/tachyfont/cmap.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/incrementalfontutils.js, run_time/src/gae_server/www/js/tachyfont/sfnt.js, run_time/src/gae_server/www/js/tachyfont/tachyfontlogger.js, run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js
Use null for an 'uninitialized' tachyfont.Report instance so tests can
reset it.
Use a unique name for the test CSS names (appears the DOM persists
across tests).
Remove a test that tests a private method.
Remove a duplicate function.
Address warnings from compiling the tests.
Mark some JsDoc types as not-null.
Slight reworking of the info in comments in a test data file.
Save the tag from the sfnt table of content as a number (in addition to
as a string).
=> Add/use accessor functions to private variables.

run_time/src/gae_server/www/js/tachyfont/backendservice.js, run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js, run_time/src/gae_server/www/js/tachyfont/cff.js, run_time/src/gae_server/www/js/tachyfont/sfnt.js
- in readDataView use the DataView byteOffset.
In cff.js
- in the constructor pass in the offset instead of a
TableOfContentsEntry
- create the binaryFontEditor in the constructor
- remove the initBinaryEditor routine
- remove some debug statements
- add convenience routines
- getCharStringIndex
- getTopDictOperand
In sfnt.js
- add a sorted (by file offset) table of contents
- handle table allocation sizes separately from the table size
- allocation size = table size + padding size
- when replacing a table size the padding to align the next table on a
long
- add convenience routines
- getTableEntry
- getTableOffset
- rename getTable to getTableData as it gets the data
- rename getTableOfContents to parseTableOfContents
- it actually parses the table of contents
- avoid possible confusion …
=> In binaryfonteditor.js

run_time/src/gae_server/www/js/tachyfont/backendservice.js, run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js, run_time/src/gae_server/www/js/tachyfont/glyphbundleresponse.js
In glyphbundleresponse.js
- add a GlyphData object
- process the glyph bytes into objects
- sort the GlyphData objects in an array
In backendservice.js
- move processing of the count and flags to
tachyfont.GlyphBundleResponse
Minor Closure annotation changes.
=> Process the glyph request bytes into a sorted array of objects.

run_time/src/gae_server/www/js/tachyfont/glyphbundleresponse.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
In sfnt.js:
- add CompactOffsets which will be used by Compact TachyFOnt
- define some table tags
- rename newFontData to newFontBytes since it is an Uint8Array
- add a convience routine
- getTableLength
=> add CompactOffsets which will be used by Compact TachyFOnt

run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js, run_time/src/gae_server/www/js/tachyfont/browser_chrome.js, run_time/src/gae_server/www/js/tachyfont/cff.js, run_time/src/gae_server/www/js/tachyfont/cff_dict.js, run_time/src/gae_server/www/js/tachyfont/cff_index.js, run_time/src/gae_server/www/js/tachyfont/fontsinfo.js, run_time/src/gae_server/www/js/tachyfont/glyphbundleresponse.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/incrementalfontutils.js, run_time/src/gae_server/www/js/tachyfont/sfnt.js, run_time/src/gae_server/www/js/tachyfont/webfonttailor.js
Change tachyfont.CffDict.OperandsOperatorSet from class to record type.
Change tachyfont.CffDict.Operator to a lookup table.
Change CffIndex types to enum.
Put variable declarations on separate lines.
Minor changes to code.
Minor changes to comments.
=> Changes for readability.

run_time/src/gae_server/www/js/tachyfont/tachyfont.js
=> Separate the window.onerror reports blocked by CORS from those with

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
reports. See https://bugs.chromium.org/p/v8/issues/detail?id=3093
Remove commented out lines from last checkin.
=> Add a .thenCatch to deal with a change to suppress debugging error

run_time/src/gae_server/www/js/tachyfont/fontinfo.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/incrementalfontutils.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js
Add a "shouldLoad" member to FontINfo.
Add the font size (in bytes) to FontInfo.
- add an optional size parameter (convert to mandatory later)
- set the default size to 5M
Make getDbName callable without needing a incrementalFont.obj.
Reverse the calls to try and diagnose why the KNOWN_WINDOW_ON_ERROR
and KNOWN_WINDOW_ON_ERROR rates are so different.
=> Only load a TachyFont is there is enough available storage.

run_time/src/gae_server/www/js/tachyfont/cmap.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/persist_idb.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js
check storage font by font.
Only report "not enough storage" once (not once per font).
=> If there is enough available storage to store all fonts then do not

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
=> Get the Prelude Blob URL so it will be freed when a new Blob URL is

run_time/src/gae_server/www/js/tachyfont/persist_idb.js
=> To enable immediate testing pretend that the data is already a day old

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js
On first page load set the font.  
If Prelude already set the font then this is not necessary but if there
is any issue with Prelude then this is a safety move.
Add a global check for stable persistent store.
Reorder the initialization code so the Prelude reports get sent earlier.
=> Add a global check for stable persistent store.

run_time/src/gae_server/www/js/tachyfont/binaryfonteditor.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/typedefs.js
Move the base font header parsing completely into BinaryFontEditor.
=> Move the cmap parsing into the base font header parsing.

run_time/src/gae_server/www/js/tachyfont/cmap.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/persist_idb.js
Compact TachyFont.
Minor tweaks to IncrementalFont getBaseFontFromUrl.
Use tachyfont.typedef.FileInfo instead Object.
=> Make IncrementalFont processUrlBase static so it can be reused by

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js, run_time/src/gae_server/www/js/tachyfont/typedefs.js
only URL parameter).
Add code to fetch Compact TachyFont from a URL (work in progress).
Add code to fetch Compact TachyFont from persistence.
Make tachyfont.IncrementalFont.Log public so it can be used in tests.
=> Add code to load/fetch the Compact TachyFont (disabled behind a debug

run_time/src/gae_server/www/js/tachyfont/tachyfont.js
Rename 'id' to 'fontId'.
Force the clang formatter to use more consistent line wrapping.
Split out the defines from tachyfontutils.js into tachyfont_define.js
=> Add routines to get/put data to IndexedDb.

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js, run_time/src/gae_server/www/js/tachyfont/typedefs.js
Add code to write the Compact data in a single call.
Move getCompactFont from tachyfont.js to incrementalfont.js.
In incrementalfont.js add a member "compactCharList".
Change key "data" to "fontBytes" in
tachyfont.typedef.CompactFontWorkingData.
=> Fetch the Compact data in a single call.

run_time/src/gae_server/www/js/tachyfont/compactcff.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js
Separate the glyphIdToCodeMap logic into a subroutine.
=> Make injectChars a simple subroutine by moving the promise code into the caller.

run_time/src/gae_server/www/js/tachyfont/persist_idb.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js
Add error reports to (temporarily) verify the Compact TachyFonts tables creation.
Remove the "if (goog.DEBUG)" around the code to initially load the
fonts.
=> Enable Compact TachyFont table creation.

run_time/src/gae_server/www/js/tachyfont/synchronous_resolution_promise.js
- IndexedDb transactions require continous / uninterrupted calls.
- The goog.Promise class has asynchronous resolution which allows other promises to 'interrupt' and this cause the transactions to fail.
This Promise class implements synchronous resolution to to make it compatible with IndexedDb.
=> Add a Promise class that is compatible with IndexedDb transactions.

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/persist_idb.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfontpromise.js, run_time/src/gae_server/www/js/tachyfont/tachyfontset.js
Remove an unneeded promise layer in tachyfont.loadFonts_loadAndUse_.
Remove some 'error' reports used to report successes.
Minor cleanups
=> Use .thenAlways to release ChainedPromises.

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/persist_idb.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfont_defines.js
Remove some compact 'phase in' controls.
Fix the error handling in tachyfont.loadFonts_loadAndUse_.
Add a warning flag for unused code.
Change the tachyfont.reportError to accept optional inputs.
=> Remove some non-compact code.

run_time/src/gae_server/www/js/tachyfont/cmap.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/incrementalfontutils.js, run_time/src/gae_server/www/js/tachyfont/typedefs.js
- FileInfo is only used during character data injection.
- FileInfo holds ~4MB memory so only bring it into memory during injection.
- Move getGlyphToCodeMap into incrementalfontutils.js
Set explicit non-nullability in various places.
=> Beginning to decouple FileInfo from IncrementalFont.

run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/sparse_bit_array.js
Storing this info in a Javascript associative map (object) takes ~2MB per font.
The sparse bit array takes ~70K.
Note: as a caution this code currently uses the old style storage which takes up significant memory. Once this new class has baked for a while the old style storage should be removed to save memory.
=> Use a sparse bit array to store the list of characters in the font.

run_time/src/gae_server/www/js/tachyfont/sparse_bit_array.js
It was removed but then rolled back due to a 4% increase in CALC_NEEDED_CHARS.
=> Slowly re-removing the code for the alternateBitInfo.

run_time/src/gae_server/www/js/tachyfont/fontinfo.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/prelude_info.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js
Export the FontInfo constructor so prelude will be able to use it.
To ease testing make the prelude tests closure files.
Remove the placeholder_test_data.js as it is no longer used.
=> In incrementalfont.js use PreludeInfo to get the prelude data.

run_time/src/gae_server/www/js/tachyfont/browser_chrome.js, run_time/src/gae_server/www/js/tachyfont/demobackendservice.js, run_time/src/gae_server/www/js/tachyfont/fontinfo.js, run_time/src/gae_server/www/js/tachyfont/googlebackendservice.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/incrementalfontutils.js, run_time/src/gae_server/www/js/tachyfont/launcher.js, run_time/src/gae_server/www/js/tachyfont/merged_data.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfontset.js, run_time/src/gae_server/www/js/tachyfont/webfonttailor.js
Change familyName to cssFontFamily when it is used for the CSS font-family.
Change familyName to fontFamily when it is the font's family name.
=> Variable renaming. No functional changes.

run_time/src/gae_server/www/js/tachyfont/error_report.js, run_time/src/gae_server/www/js/tachyfont/incrementalfont.js, run_time/src/gae_server/www/js/tachyfont/metric_report.js, run_time/src/gae_server/www/js/tachyfont/tachyfont.js, run_time/src/gae_server/www/js/tachyfont/tachyfontreporter.js, run_time/src/gae_server/www/js/tachyfont/tachyfontset.js
Create metric and error report objects.
Pass error id separately from font id.
Modify the reporter code to use the metric/error objects.
=> Prepare metric/error reporting to be backend specific.

run_time/src/gae_server/www/js/tachyfont/error_report.js, run_time/src/gae_server/www/js/tachyfont/metric_report.js
The field names need to match the protobuf field names.
=> Protect the field names from being changed by the compiler.
